//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.Distance_Calculator_Client.ServiceReferenceCalcDistance {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCalcDistance.IServiceCalcDistance")]
    public interface IServiceCalcDistance {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalcDistance/CalcDistance", ReplyAction="http://tempuri.org/IServiceCalcDistance/CalcDistanceResponse")]
        double CalcDistance(int startPointX, int startPointY, int endPointX, int endPointY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalcDistance/CalcDistance", ReplyAction="http://tempuri.org/IServiceCalcDistance/CalcDistanceResponse")]
        System.Threading.Tasks.Task<double> CalcDistanceAsync(int startPointX, int startPointY, int endPointX, int endPointY);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCalcDistanceChannel : _02.Distance_Calculator_Client.ServiceReferenceCalcDistance.IServiceCalcDistance, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCalcDistanceClient : System.ServiceModel.ClientBase<_02.Distance_Calculator_Client.ServiceReferenceCalcDistance.IServiceCalcDistance>, _02.Distance_Calculator_Client.ServiceReferenceCalcDistance.IServiceCalcDistance {
        
        public ServiceCalcDistanceClient() {
        }
        
        public ServiceCalcDistanceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCalcDistanceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCalcDistanceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCalcDistanceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalcDistance(int startPointX, int startPointY, int endPointX, int endPointY) {
            return base.Channel.CalcDistance(startPointX, startPointY, endPointX, endPointY);
        }
        
        public System.Threading.Tasks.Task<double> CalcDistanceAsync(int startPointX, int startPointY, int endPointX, int endPointY) {
            return base.Channel.CalcDistanceAsync(startPointX, startPointY, endPointX, endPointY);
        }
    }
}
